config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :promotions, only: [:index, :new, :create, :show] do
    member do
      get :print
    end
  end

  resources :cards, only: [:update]

  root 'home#index'

  get '/:token', to: 'promotions#redeem', constraints: {token: /.{10}/}
end

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= active_link_to 'Promos', root_path, active: :exclusive, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= active_link_to 'New Promotion', new_promotion_path %></li>
          <li><%= active_link_to 'Promotions', promotions_path %></li>
        <% else %>
          <li><%= active_link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= active_link_to 'Sign In', new_user_session_path %></li>
        <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= active_link_to 'Logout', destroy_user_session_path, method: :delete %>
      <% end %>
    </ul>
    </div>
  </div>
</nav>