config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :promotions, only: [:index, :new, :create, :show] do
    member do
      get :print
    end
  end

  resources :cards, only: [:update]

  root 'home#index'

  get '/:token', to: 'promotions#redeem', constraints: {token: /.{10}/}
end

app/models/promotion.rb
class Promotion < ActiveRecord::Base
  extend FriendlyId
  
  after_create :create_card

  friendly_id :name, use: [:slugged, :finders]

  attr_accessor :code_quantity, :code_unique

  belongs_to :user

  has_many :attachments, as: :attachable
  has_many :codes, dependent: :destroy
  has_many :redemptions, through: :codes
  has_one :card

  accepts_nested_attributes_for :attachments
  accepts_nested_attributes_for :codes

  TOTAL_ATTACHMENT_FILE_SIZE = 20
  
  enum status: [ :pending, :active ]

  validates_presence_of :user, :name
  validates_length_of :message, maximum: 500

  validates :code_quantity, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 100 }

  def active_codes
    codes.where(status: 1)
  end

  def code_quantity
    @code_quantity.to_i
  end

  private

  def create_card
    Card.create!(promotion: self)
  end

end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
  before_action :user_signed_in?, except: [:redeem]
  layout :resolve_layout

  def index
    @promotions = current_user.promotions
  end

  def new
    @promotion = params[:promotion] ? Promotion.new(promotion_params) : Promotion.new
    @attachment = @promotion.attachments.build
  end

  def create
    @promotion = Promotion.new(promotion_params)
    @promotion.user = current_user
    @promotion.status = 'active'
    Promotion.transaction do
      @promotion.save
      begin
        params[:attachments][:attachment].each do |a|
          @attachment = @promotion.attachments.create!(attachment: a)
        end
        CodeGenerator.new(params[:promotion][:code_unique], params[:promotion][:code_quantity], @promotion).generate
        redirect_to promotion_path(@promotion), notice: 'Successfully created promotion'
      rescue
        @_errors = true
        redirect_to new_promotion_path({promotion: promotion_params}), alert: 'Sorry something went wrong. Please try again'
      end
      raise ActiveRecord::Rollback if @_errors
    end
  end

  def show
    @promotion = Promotion.find(params[:id])
    locations = @promotion.redemptions.pluck(:location)
    @locations = Location.map_information(locations).to_json
    @dates = Location.date_information(@promotion.redemptions).to_json
  end

  def print
    @promotion = Promotion.find(params[:id])
  end

  def redeem
    @code = Code.where(token: params[:token]).take
    if @code.active?
      if @code.redeem(request.remote_ip)
        @promotion = @code.promotion
      end
    else
      redirect_to root_path, notice: 'Sorry that code has already been used'
    end
  end

  private
  def resolve_layout
    case action_name
    when 'print'
      'print'
    else
      'application'
    end
  end

  def promotion_params
    params.require(:promotion).permit(:code_quantity, :name, :message, attachment_attributes: [:attachment])
  end
end

app/helpers/promotion_helper.rb
module PromotionHelper
  def redeemed(codes)
    "#{codes.where(status: 2).count}/#{codes.count}"
  end
end

app/views/promotions/_print_promo.html.erb
<div class='business-card'>
  <div class='header' style="background-color:<%= card.header_color %>">
    <h1 class='promotion-name'><%= card.header_text %></h1>
  </div>
  <div class='content' style="background-color: <%= card.content_color %>">
    <p class='promotion-content'><%= card.content_text %></p>
    <p class='promotion-redeem'>Redeem at <%= "www.promos.io/#{code.token}" %></p>
  </div>
</div>

app/views/promotions/index.html.erb
<% @promotions.each do |p| %>
  <%= link_to p.name, promotion_path(p) %>
<% end %>

app/views/promotions/new.html.erb
<h1>Create a new promotion</h1>

<%= simple_form_for @promotion do |f| %>
  <%= f.input :name %>
  <%= f.input :message, 
    hint: "This is a message to show to the user once they've redeemed your code",
    label: "Thank you message"
  %>
<%= f.input :code_unique, label: 'Unique or Single', as: :radio_buttons, collection: Code::TYPES, checked: 'unique' %>
  <%= f.input :code_quantity, label: 'Code Quantity' %>
  <%= f.simple_fields_for :attachments do |p| %>
    <%= p.file_field :attachment, multiple: true, name: "attachments[attachment][]", label: "Attachments" %>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/promotions/print.html.erb
<% content_for :extra_head do %>
  <style>
    @media print {
    .container, .headers {
      display: none;
    }
    .business-cards {
      display: block !important;
    }
    }
  </style>
<% end %>
<h1>Print or Customise your Promo cards</h1>
<div class='row'>
<div class='preview-card col-md-6'>
  <p>Preview of your promo card</p>
  <%= render partial: "print_promo", locals: {code: @promotion.active_codes.limit(1).take, card: @promotion.card} %>
</div>
<div class='customise-card col-md-6'>
  <%= simple_form_for @promotion.card do |f| %>
    <%= f.input :header_text %>
    <%= f.input :content_text %>
    <%= f.input :header_color %>
    <%= f.input :content_color %>
    <%= f.submit 'Update card', class: 'btn btn-primary' %>
  <% end %>
  <button class='reset btn btn-default'>Reset</button>
</div>
</div>
<% content_for :printable do %>
<div class='business-cards container'>
  <%= render partial: "print_promo", collection: @promotion.active_codes, as: :code, locals: {card: @promotion.card}%>
</div>
<% end %>

<% content_for :extra_footer do %>
  <script>
  var header_text, content_text, header, content,
    original_header_text, original_content_text, original_header_color, original_content_color;
    $(function() {
        header_text = $('.preview-card h1.promotion-name');
        content_text = $('.preview-card p.promotion-content');
        header = $('.preview-card .header');
        content = $('.preview-card .content');
        original_header_text = "<%= @promotion.card.header_text %>";
        original_content_text = "<%= @promotion.card.content_text %>";
        original_header_color = "<%= @promotion.card.header_color %>";
        original_content_color = "<%= @promotion.card.content_color %>";
        $('#card_header_color, #card_content_color').colorPicker({
          onColorChange: function(id, newValue) {
            switch(id) {
            case 'card_header_color':
              set_background_color(header, newValue);
              break;
            case 'card_content_color':
              set_background_color(content, newValue);
              break;
            }
          }
        });
        $('.reset').click(restoreDefaults);
        $('.customise-card form').on('input', function(e) {
          switch (e.target.id) {
          case 'card_header_text':
            set_value(header_text, e.target.value, original_header_text);
            break;
          case 'card_content_text':
            set_value(content_text, e.target.value, original_content_text);
            break;
          }
        });
    });

    function set_background_color(element, value) {
      element.css('background-color', value);
    }

    function restoreDefaults() {
      set_value(header_text, original_header_text);
      set_value(content_text, original_content_text);
      set_background_color(header, original_header_color);
      $('#card_header_color').val(original_header_color);
      $('#card_header_color').parent().find('.colorPicker-picker').css('background-color', original_header_color);
      set_background_color(content, original_content_color);
      $('#card_content_color').val(original_content_color);
      $('#card_content_color').parent().find('.colorPicker-picker').css('background-color', original_content_color);
    }

    function set_value(element, value, original) {
      if (value.length <= 0) {
        element.text(original);
      } else {
      element.text(value);
      }
    }
  </script>
<% end %>

app/views/promotions/redeem.html.erb
<p><%= @promotion.message %></p>

app/views/promotions/show.html.erb
<ul class="nav nav-pills">
  <li class='active' id='#map-link'><a href='#'>World Map</a></li>
  <li id='#date-link'><a href='#'>Date Data</a></li>
</ul>
<div id='graphic'></div>
<p><%= redeemed(@promotion.codes) %> codes redeemed</p>
<li><%= link_to 'Print promotion cards', print_promotion_path(@promotion) %></li>

<% content_for :extra_footer do %>
  <script>
  var height = $(window).height() / 2;
$(function() {
    $('#graphic').height(height);
    $('.nav-pills li').click(function(e) {
      var target = e.target.parentElement;
      if ($(target).hasClass('active')) {
        return true;
        } else {
          $('.nav-pills li').removeClass('active');
          $(target).addClass('active');
          updateGraphic(target);
        }
    });
    makeMap('<%= raw(@locations) %>');
  });
function updateGraphic(target) {
  $('#graphic').html('');
  switch(target.id) {
    case '#map-link':
      makeMap('<%= raw(@locations) %>');
      break;
    case '#date-link':
      makeDates('<%= raw(@dates) %>');
      break;
  }
}
  </script>
<% end %>